/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ssydoruk.confservutils;

import com.genesyslab.platform.commons.*;
import java.util.*;
import org.apache.commons.lang3.*;
import org.apache.logging.log4j.*;

/**
 *
 * @author stepan_sydoruk
 */
public class BussAttr extends javax.swing.JPanel implements ISearchCommon {

    /**
     * Creates new form AppByDBID
     */
    public BussAttr() {
        initComponents();
        rbShortOutput.setSelected(true);
        cbAttr.setSelected(true);
        cbAttrValue.setSelected(true);

    }

    private static final Logger logger = Main.getLogger();

    public boolean iscbAttrSelected() {
        return cbAttr.isSelected();
    }

    public boolean iscbAttrValueSelected() {
        return cbAttrValue.isSelected();
    }

    public boolean isCaseSensitive() {
        return cbCaseSensitive.isSelected();
    }

    public boolean isRegex() {
        return cbIsRegex.isSelected();
    }

    public boolean isFullOutputSelected() {
        return rbFullOutput.isSelected();
    }

    private GEnum cfgObjType(Object o) {
        if (o instanceof String) {
            return null;
        } else {
            return ((CfgObjectTypeMenu) o).getType();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        cbAttr = new javax.swing.JCheckBox();
        cbAttrValue = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfObjectName = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        rbFullOutput = new javax.swing.JRadioButton();
        rbShortOutput = new javax.swing.JRadioButton();
        cbIsRegex = new javax.swing.JCheckBox();
        cbCaseSensitive = new javax.swing.JCheckBox();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        cbAttr.setText("Business attribute");
        jPanel7.add(cbAttr);

        cbAttrValue.setText("Business Attribute value");
        jPanel7.add(cbAttrValue);

        add(jPanel7);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setText("Name");
        jPanel6.add(jLabel5);

        tfObjectName.setEditable(true);
        jPanel6.add(tfObjectName);

        add(jPanel6);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        buttonGroup1.add(rbFullOutput);
        rbFullOutput.setText("Print full output");
        jPanel4.add(rbFullOutput);

        buttonGroup1.add(rbShortOutput);
        rbShortOutput.setText("Print abbreviated output");
        jPanel4.add(rbShortOutput);

        cbIsRegex.setText("Regular expression");
        jPanel4.add(cbIsRegex);

        cbCaseSensitive.setText("Case sensitive");
        jPanel4.add(cbCaseSensitive);

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public String getName() {
        return Utils.swing.Swing.checkBoxSelection(tfObjectName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbAttr;
    private javax.swing.JCheckBox cbAttrValue;
    private javax.swing.JCheckBox cbCaseSensitive;
    private javax.swing.JCheckBox cbIsRegex;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton rbFullOutput;
    private javax.swing.JRadioButton rbShortOutput;
    private javax.swing.JComboBox<String> tfObjectName;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getSearchSummary() {
        StringBuilder buf = new StringBuilder();

        buf.append("Search for ");
        ArrayList<String> arr = new ArrayList();
        if (iscbAttrSelected()) {
            arr.add("attribute");
        }
        if (iscbAttrValueSelected()) {
            arr.add("attribute value");
        }
        buf.append(StringUtils.join(arr, ", "));
        buf.append(" \"").append(getName()).append("\"");
        buf.append(" rx[").append(isRegex() ? "yes" : "no").append("]");
        buf.append(" CaSe[").append(isCaseSensitive() ? "yes" : "no").append("]");
        buf.append("; ").append(isFullOutputSelected() ? "full" : "short").append(" output");
        return buf.toString();

    }

    @Override
    public void setChoices(Collection<String> choices) {
        Utils.swing.Swing.setChoices(tfObjectName, choices);

    }

    @Override
    public Collection<String> getChoices() {
        return Utils.swing.Swing.getChoices(tfObjectName);
    }

}
