/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ssydoruk.confservutils;

import Utils.FileUtils;
import java.io.File;
import java.util.Enumeration;
import java.util.Iterator;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;

/**
 *
 * @author ssydoruk
 */
public class CSVtoHTMLDialog extends javax.swing.JPanel {

    private final CSVConvertDialog dlg;

    /**
     * Creates new form CSVtoHTMLDialog
     */
    public CSVtoHTMLDialog(CSVConvertDialog aThis) {
        initComponents();
        dlg = aThis;
        setSize(500, getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOpenAction = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfCSVFile = new javax.swing.JTextField();
        btSelectCSV = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfOutputFile = new javax.swing.JTextField();
        btSelectOutputHTML = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfCSSFile = new javax.swing.JTextField();
        btSelectCSS = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfJSScript = new javax.swing.JTextField();
        btSelectJSScript = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rbDefaultBrowser = new javax.swing.JRadioButton();
        rbFolder = new javax.swing.JRadioButton();
        rbDoNothing = new javax.swing.JRadioButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("CSV file to convert");
        jLabel1.setFocusable(false);
        jPanel1.add(jLabel1);
        jPanel1.add(tfCSVFile);

        btSelectCSV.setText("...");
        btSelectCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectCSVActionPerformed(evt);
            }
        });
        jPanel1.add(btSelectCSV);

        add(jPanel1);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Output file");
        jLabel2.setFocusable(false);
        jPanel3.add(jLabel2);
        jPanel3.add(tfOutputFile);

        btSelectOutputHTML.setText("...");
        btSelectOutputHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectOutputHTMLActionPerformed(evt);
            }
        });
        jPanel3.add(btSelectOutputHTML);

        add(jPanel3);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("CSS file");
        jLabel4.setFocusable(false);
        jPanel6.add(jLabel4);
        jPanel6.add(tfCSSFile);

        btSelectCSS.setText("...");
        btSelectCSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectCSSActionPerformed(evt);
            }
        });
        jPanel6.add(btSelectCSS);

        add(jPanel6);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setText("Processing script");
        jLabel5.setFocusable(false);
        jPanel7.add(jLabel5);
        jPanel7.add(tfJSScript);

        btSelectJSScript.setText("...");
        btSelectJSScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectJSScriptActionPerformed(evt);
            }
        });
        jPanel7.add(btSelectJSScript);

        add(jPanel7);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Once done, open in..."));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        bgOpenAction.add(rbDefaultBrowser);
        rbDefaultBrowser.setText("default browser");
        jPanel4.add(rbDefaultBrowser);

        bgOpenAction.add(rbFolder);
        rbFolder.setText("Folder");
        jPanel4.add(rbFolder);

        bgOpenAction.add(rbDoNothing);
        rbDoNothing.setText("(do nothing)");
        jPanel4.add(rbDoNothing);

        jPanel2.add(jPanel4);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void btSelectOutputHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectOutputHTMLActionPerformed
        File selectSingleFile = FileUtils.selectSingleFile(dlg, null, "HTML output file", "HTML files", new String[]{"htm", "html"});
        if (selectSingleFile != null) {
            tfOutputFile.setText(selectSingleFile.getAbsolutePath());
        }

    }//GEN-LAST:event_btSelectOutputHTMLActionPerformed

    private void btSelectCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectCSVActionPerformed
        File selectSingleFile = FileUtils.selectSingleFile(dlg, null, "CSV file to convert", "CSV files", new String[]{"csv"});
        if (selectSingleFile != null) {
            tfCSVFile.setText(selectSingleFile.getAbsolutePath());
        }

    }//GEN-LAST:event_btSelectCSVActionPerformed

    private void btSelectCSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectCSSActionPerformed
        File selectSingleFile = FileUtils.selectSingleFile(dlg, null, "select CSS file", "CSS files", new String[]{"css"});
        if (selectSingleFile != null) {
            tfCSSFile.setText(selectSingleFile.getAbsolutePath());
        }

    }//GEN-LAST:event_btSelectCSSActionPerformed

    private void btSelectJSScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectJSScriptActionPerformed
        File selectSingleFile = FileUtils.selectSingleFile(dlg, null, "JS script", "Javascript files", new String[]{"js"});
        if (selectSingleFile != null) {
            tfJSScript.setText(selectSingleFile.getAbsolutePath());
        }

    }//GEN-LAST:event_btSelectJSScriptActionPerformed

    public void setTexttfCSSFile(String t) {
        tfCSSFile.setText(t);
    }

    public String getTexttfCSSFile() {
        return tfCSSFile.getText();
    }

    public void setTexttfCSVFile(String t) {
        tfCSVFile.setText(t);
    }

    public String getTexttfCSVFile() {
        return tfCSVFile.getText();
    }

    public void setTexttfJSScript(String t) {
        tfJSScript.setText(t);
    }

    public String getTexttfJSScript() {
        return tfJSScript.getText();
    }

    public void setTexttfOutputFile(String t) {
        tfOutputFile.setText(t);
    }

    public String getTexttfOutputFile() {
        return tfOutputFile.getText();
    }

    public void setActiveButton(int idx) {
        int buttonCount = bgOpenAction.getButtonCount();
        int sel = (idx <= buttonCount) ? idx : 0;
        Enumeration<AbstractButton> elements = bgOpenAction.getElements();
        int i = 0;
        while (elements.hasMoreElements()) {
            JRadioButton bt = (JRadioButton) elements.nextElement();
            if (i == sel) {
                bt.setSelected(true);
                break;
            } else {
                i++;
            }
        }
    }
    
    
    public int getActiveButton() {
        Enumeration<AbstractButton> elements = bgOpenAction.getElements();
        int i = 0;
        while (elements.hasMoreElements()) {
            JRadioButton bt = (JRadioButton) elements.nextElement();
            if(bt.isSelected()){
                return i;
            } else {
                i++;
            }
        }
        return 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgOpenAction;
    private javax.swing.JButton btSelectCSS;
    private javax.swing.JButton btSelectCSV;
    private javax.swing.JButton btSelectJSScript;
    private javax.swing.JButton btSelectOutputHTML;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton rbDefaultBrowser;
    private javax.swing.JRadioButton rbDoNothing;
    private javax.swing.JRadioButton rbFolder;
    private javax.swing.JTextField tfCSSFile;
    private javax.swing.JTextField tfCSVFile;
    private javax.swing.JTextField tfJSScript;
    private javax.swing.JTextField tfOutputFile;
    // End of variables declaration//GEN-END:variables
}
