/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ssydoruk.confservutils;

import Utils.FileUtils;
import java.io.File;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import org.apache.commons.compress.utils.FileNameUtils;
import org.apache.commons.io.FilenameUtils;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author ssydoruk
 */
public class CSVtoHTMLDialog extends javax.swing.JPanel {

    private final CSVConvertDialog dlg;

    /**
     * Creates new form CSVtoHTMLDialog
     */
    public CSVtoHTMLDialog(CSVConvertDialog aThis) {
        initComponents();
        dlg = aThis;
        setSize(500, getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOpenAction = new javax.swing.ButtonGroup();
        bgCSSFile = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfCSVFile = new javax.swing.JComboBox<>();
        btSelectCSV = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfOutputFile = new javax.swing.JComboBox<>();
        btSelectOutputHTML = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfCSSFile = new javax.swing.JComboBox<>();
        btSelectCSS = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfJSScript = new javax.swing.JComboBox<>();
        btSelectJSScript = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rbDefaultBrowser = new javax.swing.JRadioButton();
        rbFolder = new javax.swing.JRadioButton();
        rbDoNothing = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        rbCSSEmbed = new javax.swing.JRadioButton();
        rbCSSExternal = new javax.swing.JRadioButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("CSV file to convert");
        jLabel1.setFocusable(false);
        jPanel1.add(jLabel1);

        tfCSVFile.setEditable(true);
        jPanel1.add(tfCSVFile);

        btSelectCSV.setText("...");
        btSelectCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectCSVActionPerformed(evt);
            }
        });
        jPanel1.add(btSelectCSV);

        add(jPanel1);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Output file");
        jLabel2.setFocusable(false);
        jPanel3.add(jLabel2);

        tfOutputFile.setEditable(true);
        jPanel3.add(tfOutputFile);

        btSelectOutputHTML.setText("...");
        btSelectOutputHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectOutputHTMLActionPerformed(evt);
            }
        });
        jPanel3.add(btSelectOutputHTML);

        add(jPanel3);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("CSS file");
        jLabel4.setFocusable(false);
        jPanel6.add(jLabel4);

        tfCSSFile.setEditable(true);
        jPanel6.add(tfCSSFile);

        btSelectCSS.setText("...");
        btSelectCSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectCSSActionPerformed(evt);
            }
        });
        jPanel6.add(btSelectCSS);

        add(jPanel6);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setText("Processing script");
        jLabel5.setFocusable(false);
        jPanel7.add(jLabel5);

        tfJSScript.setEditable(true);
        jPanel7.add(tfJSScript);

        btSelectJSScript.setText("...");
        btSelectJSScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectJSScriptActionPerformed(evt);
            }
        });
        jPanel7.add(btSelectJSScript);

        add(jPanel7);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Once done, open in..."));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        bgOpenAction.add(rbDefaultBrowser);
        rbDefaultBrowser.setText("default browser");
        jPanel4.add(rbDefaultBrowser);

        bgOpenAction.add(rbFolder);
        rbFolder.setText("Folder");
        jPanel4.add(rbFolder);

        bgOpenAction.add(rbDoNothing);
        rbDoNothing.setText("(do nothing)");
        jPanel4.add(rbDoNothing);

        jPanel2.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("CSS file"));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        bgCSSFile.add(rbCSSEmbed);
        rbCSSEmbed.setText("Embeded");
        jPanel5.add(rbCSSEmbed);

        bgCSSFile.add(rbCSSExternal);
        rbCSSExternal.setText("external");
        jPanel5.add(rbCSSExternal);

        jPanel2.add(jPanel5);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void btSelectOutputHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectOutputHTMLActionPerformed
        File selectSingleFile = FileUtils.selectSingleFile(dlg, getFileDir((String) tfOutputFile.getSelectedItem()), "HTML output file", "HTML files", new String[]{"htm", "html"});
        if (selectSingleFile != null) {
            setSelectItem(tfOutputFile, selectSingleFile.getAbsolutePath());
        }

    }//GEN-LAST:event_btSelectOutputHTMLActionPerformed

    private void btSelectCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectCSVActionPerformed

        File selectSingleFile = FileUtils.selectSingleFile(dlg, getFileDir((String) tfCSVFile.getSelectedItem()), "CSV file to convert", "CSV files", new String[]{"csv"});
        if (selectSingleFile != null) {
            setSelectItem(tfCSVFile, selectSingleFile.getAbsolutePath());
            String outputFile = tfOutputFile.getItemAt(0);
            String outputPath = "";
            String outputExt = "";
            if (StringUtils.isNotEmpty(outputFile)) {
                outputPath = FilenameUtils.getFullPath(outputFile);
                outputExt = FileNameUtils.getExtension(outputFile);
            }
            if (StringUtils.isEmpty(outputExt)) {
                outputExt = "html";
            }
            setSelectItem(tfOutputFile, FilenameUtils.concat(outputPath, FilenameUtils.getBaseName(selectSingleFile.getName()))
                    + FilenameUtils.EXTENSION_SEPARATOR + outputExt);
        }

    }//GEN-LAST:event_btSelectCSVActionPerformed

    private void btSelectCSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectCSSActionPerformed
        File selectSingleFile = FileUtils.selectSingleFile(dlg, getFileDir((String) tfCSSFile.getSelectedItem()), "select CSS file", "CSS files", new String[]{"css"});
        if (selectSingleFile != null) {
            setSelectItem(tfCSSFile, selectSingleFile.getAbsolutePath());
        }

    }//GEN-LAST:event_btSelectCSSActionPerformed

    private void btSelectJSScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectJSScriptActionPerformed
        File selectSingleFile = FileUtils.selectSingleFile(dlg, getFileDir((String) tfJSScript.getSelectedItem()), "JS script", "Javascript files", new String[]{"js"});
        if (selectSingleFile != null) {
            setSelectItem(tfJSScript, selectSingleFile.getAbsolutePath());
        }

    }//GEN-LAST:event_btSelectJSScriptActionPerformed

    public void setTexttfCSSFile(List<String> t) {
        setComboList(tfCSSFile, t);
    }

    public List<String> getTexttfCSSFile() {
        return getAllItems(tfCSSFile);
    }

    public void setTexttfCSVFile(List<String> t) {
        setComboList(tfCSVFile, t);
    }

    public List<String> getTexttfCSVFile() {
        return getAllItems(tfCSVFile);
    }

    public void setTexttfJSScript(List<String> t) {
        setComboList(tfJSScript, t);
    }

    public List<String> getTexttfJSScript() {
        return getAllItems(tfJSScript);
    }

    public void setTexttfOutputFile(List<String> t) {
        setComboList(tfOutputFile, t);
    }

    public List<String> getTexttfOutputFile() {
        return getAllItems(tfOutputFile);
    }

    public void setActiveButton(javax.swing.ButtonGroup bg, int idx) {
        int buttonCount = bg.getButtonCount();
        int sel = (idx <= buttonCount) ? idx : 0;
        Enumeration<AbstractButton> elements = bg.getElements();
        int i = 0;
        while (elements.hasMoreElements()) {
            JRadioButton bt = (JRadioButton) elements.nextElement();
            if (i == sel) {
                bt.setSelected(true);
                break;
            } else {
                i++;
            }
        }
    }

    public int getActiveButton(javax.swing.ButtonGroup bg) {
        Enumeration<AbstractButton> elements = bg.getElements();
        int i = 0;
        while (elements.hasMoreElements()) {
            JRadioButton bt = (JRadioButton) elements.nextElement();
            if (bt.isSelected()) {
                return i;
            } else {
                i++;
            }
        }
        return 0;
    }

    public ButtonGroup getBgCSSFile() {
        return bgCSSFile;
    }

    public ButtonGroup getBgOpenAction() {
        return bgOpenAction;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCSSFile;
    private javax.swing.ButtonGroup bgOpenAction;
    private javax.swing.JButton btSelectCSS;
    private javax.swing.JButton btSelectCSV;
    private javax.swing.JButton btSelectJSScript;
    private javax.swing.JButton btSelectOutputHTML;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton rbCSSEmbed;
    private javax.swing.JRadioButton rbCSSExternal;
    private javax.swing.JRadioButton rbDefaultBrowser;
    private javax.swing.JRadioButton rbDoNothing;
    private javax.swing.JRadioButton rbFolder;
    private javax.swing.JComboBox<String> tfCSSFile;
    private javax.swing.JComboBox<String> tfCSVFile;
    private javax.swing.JComboBox<String> tfJSScript;
    private javax.swing.JComboBox<String> tfOutputFile;
    // End of variables declaration//GEN-END:variables

    private File getFileDir(String text) {
        return (StringUtils.isEmpty(text) ? null : new File(FilenameUtils.getFullPath(text)));
    }

    private void setSelectItem(JComboBox<String> jcb, String s) {
        for (int i = 0; i < jcb.getItemCount(); i++) {
            if (jcb.getItemAt(i).equals(s)) {
                jcb.setSelectedIndex(i);
                return;
            }
        }
        jcb.insertItemAt(s, 0);
        jcb.setSelectedIndex(0);
    }

    private List<String> getAllItems(JComboBox<String> comboBox) {
        List<String> ret = new ArrayList<>(comboBox.getItemCount());
        for (int i = 0; i < comboBox.getItemCount(); i++) {
            ret.add(comboBox.getItemAt(i));
        }
        return ret;
    }

    private void setComboList(JComboBox<String> combo, List<String> t) {
        if (t != null && !t.isEmpty()) {
            combo.setModel(new DefaultComboBoxModel(t.toArray()));
        } else {
            combo.setModel(new DefaultComboBoxModel<>());
        }
    }
}
