/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ssydoruk.confservutils;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author stepan_sydoruk
 */
public class JSEditPanel extends javax.swing.JPanel {

	/**
	 * Creates new form JSEditPanel
	 */
	public JSEditPanel() {
		super();
		initComponents();
		loadFile(new File("/Users/stepan_sydoruk/src/ConfServUtils/jsTest.js"));
	}

	private ICSVFileChooser chooser = CICSVFileChooser.of();

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		bLoadFile = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		taScript = new javax.swing.JTextArea();

		setBorder(javax.swing.BorderFactory.createTitledBorder("JavaScript to run"));
		setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

		jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

		bLoadFile.setText("Load...");
		bLoadFile.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bLoadFileActionPerformed(evt);
			}
		});
		jPanel1.add(bLoadFile);

		jButton2.setText("classes reference");
		jPanel1.add(jButton2);

		add(jPanel1);

		jPanel2.setLayout(new java.awt.BorderLayout());

		taScript.setColumns(20);
		taScript.setRows(5);
		jScrollPane1.setViewportView(taScript);

		jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		add(jPanel2);
	}// </editor-fold>//GEN-END:initComponents

	public String getText() {
		return taScript.getText();
	}

	private void loadFile(File fileName) {
		StringBuilder txt = new StringBuilder();
		try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
			String l;
			while ((l = reader.readLine()) != null) {
				txt.append(l).append('\n');

			}
		} catch (final FileNotFoundException ex) {
			java.util.logging.Logger.getLogger(AppForm.class.getName()).log(Level.SEVERE, null, ex);
		} catch (final IOException ex) {
			java.util.logging.Logger.getLogger(AppForm.class.getName()).log(Level.SEVERE, null, ex);
		}
		taScript.setText(txt.toString());
	}

	private void bLoadFileActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bLoadFileActionPerformed
		JFileChooser _chooser = getFileChooser();

		final int returnVal = _chooser.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			loadFile(_chooser.getSelectedFile());
		}

	}// GEN-LAST:event_bLoadFileActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton bLoadFile;
	private javax.swing.JButton jButton2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea taScript;
	// End of variables declaration//GEN-END:variables

	private JFileChooser getFileChooser() {
		chooser.dlg().setFileFilter(new FileNameExtensionFilter("JS files", "js"));
		chooser.dlg().setDialogType(JFileChooser.OPEN_DIALOG);
		chooser.dlg().setMultiSelectionEnabled(false);

		return chooser.dlg();
	}
}
