/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ssydoruk.confservutils;

import static Utils.Swing.checkBoxSelection;
import Utils.Util;
import com.genesyslab.platform.configuration.protocol.types.CfgObjectType;
import java.util.Collection;

/**
 *
 * @author stepan_sydoruk
 */
public class ObjByDBID extends javax.swing.JPanel implements ISearchCommon {

    /**
     * Creates new form AppByDBID
     */
    public ObjByDBID() {
        initComponents();
        Main.loadGenesysTypes(cbObjectType, CfgObjectType.values());
        CfgObjectTypeMenu.setSelectedItem(cbObjectType, CfgObjectType.CFGApplication);

    }

    public CfgObjectType getSelectedItem() {
        Object selectedItem = cbObjectType.getSelectedItem();
        if (selectedItem instanceof CfgObjectTypeMenu) {
            return (CfgObjectType) ((CfgObjectTypeMenu) selectedItem).getType();
        } else {
            return null;
        }
    }

    public boolean isFullOutput() {
        return rbFullOutput.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfDBID = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbObjectType = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        rbFullOutput = new javax.swing.JRadioButton();
        rbShortOutput = new javax.swing.JRadioButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("DBID");
        jPanel1.add(jLabel1);

        tfDBID.setEditable(true);
        jPanel1.add(tfDBID);

        jPanel3.add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Object type");
        jPanel2.add(jLabel2);

        jPanel2.add(cbObjectType);

        jPanel3.add(jPanel2);

        add(jPanel3);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.PAGE_AXIS));

        buttonGroup1.add(rbFullOutput);
        rbFullOutput.setText("Print full output");
        jPanel9.add(rbFullOutput);

        buttonGroup1.add(rbShortOutput);
        rbShortOutput.setSelected(true);
        rbShortOutput.setText("Print abbreviated output");
        jPanel9.add(rbShortOutput);

        add(jPanel9);
    }// </editor-fold>//GEN-END:initComponents

    public int getValue() {
        Object selectedItem = tfDBID.getSelectedItem();
        return (selectedItem != null) ? Util.intOrDef(selectedItem.toString(), 0) : 0;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbObjectType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton rbFullOutput;
    private javax.swing.JRadioButton rbShortOutput;
    private javax.swing.JComboBox<String> tfDBID;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getSearchSummary() {
        return "Search for object type " + getSelectedItem() + " dbid: " + checkBoxSelection(tfDBID);
    }

    @Override
    public void setChoices(Collection<String> choices) {
        Utils.Swing.setChoices(tfDBID, choices);
    }

    @Override
    public Collection<String> getChoices() {
        return Utils.Swing.getChoices(tfDBID);
    }
}
