/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.airbnb.confservutils;

import com.genesyslab.platform.configuration.protocol.types.CfgAppType;
import com.genesyslab.platform.configuration.protocol.types.CfgEnumType;
import com.genesyslab.platform.configuration.protocol.types.CfgObjectType;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import org.apache.commons.lang3.StringUtils;
import org.apache.logging.log4j.LogManager;

/**
 *
 * @author stepan_sydoruk
 */
public class AppByOptions extends javax.swing.JPanel {

    /**
     * Creates new form AppByDBID
     */
    public AppByOptions() {
        initComponents();
        Main.loadGenesysTypes(cbApplicationType, CfgAppType.values());
        rbShortOutput.setSelected(true);
        cbCaseSensitive.setSelected(false);

    }

    public boolean isCaseSensitive() {
        return cbCaseSensitive.isSelected();
    }

    public boolean isRegex() {
        return cbIsRegex.isSelected();
    }

    public boolean isFullOutputSelected() {
        return rbFullOutput.isSelected();
    }

    /**
     *
     * @return application type if configured or null if all types
     */
    public CfgAppType getSelectedAppType() {
        Object ret = cbApplicationType.getSelectedItem();
        if (ret instanceof CfgObjectTypeMenu) {
            return (CfgAppType) ((CfgObjectTypeMenu) ret).getType();
        } else {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfSection = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfOption = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfOptionValue = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbApplicationType = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        rbFullOutput = new javax.swing.JRadioButton();
        rbShortOutput = new javax.swing.JRadioButton();
        cbIsRegex = new javax.swing.JCheckBox();
        cbCaseSensitive = new javax.swing.JCheckBox();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Section name");
        jPanel3.add(jLabel3);
        jPanel3.add(tfSection);

        add(jPanel3);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Option name");
        jPanel1.add(jLabel1);
        jPanel1.add(tfOption);

        add(jPanel1);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Option Value");
        jPanel5.add(jLabel4);
        jPanel5.add(tfOptionValue);

        add(jPanel5);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Application type");
        jPanel2.add(jLabel2);

        jPanel2.add(cbApplicationType);

        add(jPanel2);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        buttonGroup1.add(rbFullOutput);
        rbFullOutput.setText("Print full output");
        jPanel4.add(rbFullOutput);

        buttonGroup1.add(rbShortOutput);
        rbShortOutput.setText("Print abbreviated output");
        jPanel4.add(rbShortOutput);

        cbIsRegex.setText("Regular expression");
        jPanel4.add(cbIsRegex);

        cbCaseSensitive.setText("Case sensitive");
        jPanel4.add(cbCaseSensitive);

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents

    public String getSection() {
        return StringUtils.stripToNull(tfSection.getText());
    }

    public String getOption() {
        return StringUtils.stripToNull(tfOption.getText());
    }

    public String getValue() {
        return StringUtils.stripToNull(tfOptionValue.getText());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbApplicationType;
    private javax.swing.JCheckBox cbCaseSensitive;
    private javax.swing.JCheckBox cbIsRegex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton rbFullOutput;
    private javax.swing.JRadioButton rbShortOutput;
    private javax.swing.JTextField tfOption;
    private javax.swing.JTextField tfOptionValue;
    private javax.swing.JTextField tfSection;
    // End of variables declaration//GEN-END:variables
}
