/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.airbnb.confservutils;

import static Utils.Swing.checkBoxSelection;
import com.genesyslab.platform.commons.GEnum;
import java.util.ArrayList;
import java.util.Collection;
import org.apache.commons.lang3.StringUtils;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author stepan_sydoruk
 */
public class FindObject extends javax.swing.JPanel implements ISearchCommon {

    /**
     * Creates new form AppByDBID
     */
    public FindObject() {
        initComponents();

    }

    private static final Logger logger = Main.getLogger();

    public boolean isCaseSensitive() {
        return cbCaseSensitive.isSelected();
    }

    public boolean isRegex() {
        return cbIsRegex.isSelected();
    }

    public void setLabel(String s) {
        nameTitle.setText(s);
    }

    public void setCaseSensitive(boolean isCase) {
        cbCaseSensitive.setSelected(isCase);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        nameTitle = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tfObjectName = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        cbIsRegex = new javax.swing.JCheckBox();
        cbCaseSensitive = new javax.swing.JCheckBox();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setLayout(new java.awt.BorderLayout());
        jPanel7.add(nameTitle, java.awt.BorderLayout.CENTER);

        add(jPanel7);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        tfObjectName.setEditable(true);
        jPanel6.add(tfObjectName);

        add(jPanel6);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        cbIsRegex.setText("Regular expression");
        jPanel4.add(cbIsRegex);

        cbCaseSensitive.setSelected(true);
        cbCaseSensitive.setText("Case sensitive");
        jPanel4.add(cbCaseSensitive);

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public String getName() {
        return checkBoxSelection(tfObjectName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbCaseSensitive;
    private javax.swing.JCheckBox cbIsRegex;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel nameTitle;
    private javax.swing.JComboBox<String> tfObjectName;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getSearchSummary() {
        StringBuilder buf = new StringBuilder();

        buf.append("Search for ");
        ArrayList<String> arr = new ArrayList();

        buf.append(StringUtils.join(arr, ", "));
        buf.append(" \"").append(getName()).append("\"");
        buf.append(" rx[").append(isRegex() ? "yes" : "no").append("]");
        buf.append(" CaSe[").append(isCaseSensitive() ? "yes" : "no").append("]");
        return buf.toString();

    }

    @Override
    public void setChoices(Collection<String> choices) {
        Utils.Swing.setChoices(tfObjectName, choices);

    }

    @Override
    public Collection<String> getChoices() {
        return Utils.Swing.getChoices(tfObjectName);
    }

}
