/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.airbnb.confservutils;

import com.genesyslab.platform.commons.GEnum;
import com.genesyslab.platform.configuration.protocol.types.CfgAppType;
import com.genesyslab.platform.configuration.protocol.types.CfgDNType;
import com.genesyslab.platform.configuration.protocol.types.CfgEnumType;
import com.genesyslab.platform.configuration.protocol.types.CfgObjectType;
import com.genesyslab.platform.configuration.protocol.types.CfgScriptType;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Collection;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import org.apache.commons.lang3.StringUtils;
import org.apache.logging.log4j.LogManager;

/**
 *
 * @author stepan_sydoruk
 */
public class ObjByAnnex extends javax.swing.JPanel {

    /**
     * Creates new form AppByDBID
     */
    private static final String anyType = "(Any type)";

    public ObjByAnnex() {
        initComponents();
        cbObjectType.removeAllItems();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbObjectType.getModel();
        for (Object object : CfgObjectType.values()) {
            model.addElement(object);
        }
        model.insertElementAt(anyType, 0);

        cbObjectType.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    cbObjectTypeChanged(e.getItem());
                }
            }

        });

        model.setSelectedItem(anyType);
        rbShortOutput.setSelected(true);
        cbCaseSensitive.setSelected(false);

    }

    private void cbObjectTypeChanged(Object item) {
        CfgObjectType t = (CfgObjectType) cfgObjType(item);
        if (t != null) {

            if (t == CfgObjectType.CFGDN) {
                setSubtypeValues(CfgDNType.values());
                return;
            } else if (t == CfgObjectType.CFGScript) {
                setSubtypeValues(CfgScriptType.values());
                return;
            }
        }
        setSubtypeValues(null);
    }

    public boolean isCaseSensitive() {
        return cbCaseSensitive.isSelected();
    }

    public boolean isRegex() {
        return cbIsRegex.isSelected();
    }

    public boolean isFullOutputSelected() {
        return rbFullOutput.isSelected();
    }

    /**
     *
     * @return application type if configured or null if all types
     */
    public CfgObjectType getSelectedObjType() {
        Object ret = cbObjectType.getSelectedItem();
        if (ret instanceof String) {
            return null;
        } else {
            return (CfgObjectType) ret;
        }
    }

    /**
     *
     * @return application type if configured or null if all types
     */
    public GEnum getSelectedObjSubType() {
        return cfgObjType(cbObjectSubtype.getSelectedItem());
    }

    private GEnum cfgObjType(Object o) {
        if (o instanceof String) {
            return null;
        } else {
            return (GEnum) o;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfObjectName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfSection = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfOption = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfOptionValue = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbObjectType = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbObjectSubtype = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        rbFullOutput = new javax.swing.JRadioButton();
        rbShortOutput = new javax.swing.JRadioButton();
        cbIsRegex = new javax.swing.JCheckBox();
        cbCaseSensitive = new javax.swing.JCheckBox();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setText("Object name");
        jPanel6.add(jLabel5);
        jPanel6.add(tfObjectName);

        add(jPanel6);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Section name");
        jPanel3.add(jLabel3);
        jPanel3.add(tfSection);

        add(jPanel3);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Option name");
        jPanel1.add(jLabel1);
        jPanel1.add(tfOption);

        add(jPanel1);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Option Value");
        jPanel5.add(jLabel4);
        jPanel5.add(tfOptionValue);

        add(jPanel5);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Object type");
        jPanel2.add(jLabel2);

        jPanel2.add(cbObjectType);

        add(jPanel2);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setText("Object subtype");
        jPanel7.add(jLabel6);

        jPanel7.add(cbObjectSubtype);

        add(jPanel7);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        buttonGroup1.add(rbFullOutput);
        rbFullOutput.setText("Print full output");
        jPanel4.add(rbFullOutput);

        buttonGroup1.add(rbShortOutput);
        rbShortOutput.setText("Print abbreviated output");
        jPanel4.add(rbShortOutput);

        cbIsRegex.setText("Regular expression");
        jPanel4.add(cbIsRegex);

        cbCaseSensitive.setText("Case sensitive");
        jPanel4.add(cbCaseSensitive);

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents

    public String getSection() {
        return StringUtils.stripToNull(tfSection.getText());
    }

    public String getName() {
        return StringUtils.stripToNull(tfObjectName.getText());
    }

    public String getOption() {
        return StringUtils.stripToNull(tfOption.getText());
    }

    public String getValue() {
        return StringUtils.stripToNull(tfOptionValue.getText());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbCaseSensitive;
    private javax.swing.JCheckBox cbIsRegex;
    private javax.swing.JComboBox<String> cbObjectSubtype;
    private javax.swing.JComboBox<String> cbObjectType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton rbFullOutput;
    private javax.swing.JRadioButton rbShortOutput;
    private javax.swing.JTextField tfObjectName;
    private javax.swing.JTextField tfOption;
    private javax.swing.JTextField tfOptionValue;
    private javax.swing.JTextField tfSection;
    // End of variables declaration//GEN-END:variables

    private void setSubtypeValues(Collection values) {
        cbObjectSubtype.removeAllItems();
        cbObjectSubtype.setEnabled((values != null));
        if (values != null) {
            DefaultComboBoxModel model = (DefaultComboBoxModel) cbObjectSubtype.getModel();
            for (Object object : values) {
                model.addElement(object);
            }
            model.insertElementAt(anyType, 0);
            cbObjectSubtype.setSelectedIndex(0);
            cbObjectSubtype.setEnabled(true);
        }

    }
}
