/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.airbnb.confservutils;

import com.genesyslab.platform.configuration.protocol.types.CfgObjectType;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author stepan_sydoruk
 */
public class ObjByDBID extends javax.swing.JPanel {

    /**
     * Creates new form AppByDBID
     */
    public ObjByDBID() {
        initComponents();
        Main.loadGenesysTypes(cbObjectType, CfgObjectType.values());
        CfgObjectTypeMenu.setSelectedItem(cbObjectType, CfgObjectType.CFGApplication);

    }

    public CfgObjectType getSelectedItem() {
        Object selectedItem = cbObjectType.getSelectedItem();
        if (selectedItem instanceof CfgObjectTypeMenu) {
            return (CfgObjectType) ((CfgObjectTypeMenu) selectedItem).getType();
        } else {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfDBID = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbObjectType = new javax.swing.JComboBox<>();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("DBID");
        jPanel1.add(jLabel1);

        tfDBID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(tfDBID);

        add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Object type");
        jPanel2.add(jLabel2);

        jPanel2.add(cbObjectType);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    public int getValue() {
        return ((Number) tfDBID.getValue()).intValue();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbObjectType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField tfDBID;
    // End of variables declaration//GEN-END:variables
}
